concrete GreetingsCze of Greetings = SentencesCze [Greeting,mkGreeting] ** {
lin
  GBye = mkGreeting "ahoj" ;
  GCheers = mkGreeting "na zdraví" ;
  GDamn = mkGreeting "sakra" ;
  GExcuse = mkGreeting "promiň" ;
  GExcusePol = mkGreeting "promiňte" ;
  GGoodDay = mkGreeting "dobrý den" ;
  GGoodEvening = mkGreeting "dobrý večer" ;
  GGoodMorning = mkGreeting "dobré ráno" ;
  GGoodNight = mkGreeting "dobrou noc" ;
  GGoodbye = mkGreeting "na shledanou" ;
  GHello = mkGreeting "ahoj" ;
  GHelp = mkGreeting "pomoc" ;
  GHowAreYou = mkGreeting "jak se máš" ;
  GLookOut = mkGreeting "pozor" ;
  GNiceToMeetYou = mkGreeting "těší mě" ;
  GPleaseGive = mkGreeting "prosím" ;
  GPleaseGivePol = mkGreeting "prosím" ;
  GSeeYouSoon = mkGreeting "brzy na shledanou" ;
  GSorry = mkGreeting "promiň" ;
  GSorryPol = mkGreeting "promiňte" ;
  GThanks = mkGreeting "děkuji" ;
  GTheCheck = mkGreeting "účet prosím" ;
  GCongratulations = mkGreeting "blahopřeji" ;
  GHappyBirthday = mkGreeting "všechno nejlepší k narozeninám" ;
  GGoodLuck = mkGreeting "hodně štěstí" ;
  GWhatTime = mkGreeting "kolik je hodin" ;
}
